//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""Steering Wheel"",
            ""id"": ""5c0c9a1f-1601-450d-b71f-de4ab17a4d9b"",
            ""actions"": [
                {
                    ""name"": ""DpadDown"",
                    ""type"": ""Button"",
                    ""id"": ""7acc7198-bfb6-44c5-bff8-67dd01f71b5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DpadUp"",
                    ""type"": ""Button"",
                    ""id"": ""810eff6b-adfc-4666-95e7-0fb95b127d42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DpadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""6a1e6a19-abe4-4607-8a22-6e180686512c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DpadRight"",
                    ""type"": ""Button"",
                    ""id"": ""f4fd3b80-da8f-42ce-810a-033fbfa03383"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""56050fbd-5721-4a0c-84ff-dcfc4720d157"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Button"",
                    ""id"": ""7b938e0f-1d9c-4bb5-ba86-578d67cee7a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L3"",
                    ""type"": ""Button"",
                    ""id"": ""8679145d-a7b2-4b00-9ab3-0b7d689f1ccd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""297b8d69-10d5-4201-a8a6-8437244bbfea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R2"",
                    ""type"": ""Button"",
                    ""id"": ""650c67fc-1c71-4263-a9e6-351b6f4eca2f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R3"",
                    ""type"": ""Button"",
                    ""id"": ""6c175446-4fed-4241-9239-ef55f6e0a84a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Plus"",
                    ""type"": ""Button"",
                    ""id"": ""3973cb4e-f819-43b9-ae95-609bd7d1eecb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Minus"",
                    ""type"": ""Button"",
                    ""id"": ""cc8db32f-c685-4406-b074-8e746b68c2ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PS"",
                    ""type"": ""Button"",
                    ""id"": ""bed965c0-83ba-44dd-83cc-1c2e78e09f35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Share"",
                    ""type"": ""Button"",
                    ""id"": ""14c4cac8-7845-40e1-811a-324539680623"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Options"",
                    ""type"": ""Button"",
                    ""id"": ""1743650c-ad1e-4716-8e87-049faae2bd14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Triangle"",
                    ""type"": ""Button"",
                    ""id"": ""863c7e07-3768-400b-9fbc-2e132f148186"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Square"",
                    ""type"": ""Button"",
                    ""id"": ""67edf388-dec5-4adf-a117-7096c78bab2c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cross"",
                    ""type"": ""Button"",
                    ""id"": ""1e607623-eb6b-4b8f-90e8-edf7c0e60324"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Circle"",
                    ""type"": ""Button"",
                    ""id"": ""e70e2fd2-bc16-4f22-9bde-983266ccb3df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wheel"",
                    ""type"": ""Button"",
                    ""id"": ""101bc4fc-f56a-4a07-8fcf-d97f0a202562"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WheelMiddle"",
                    ""type"": ""Button"",
                    ""id"": ""7c79a3cf-0b99-43c1-8b08-84061b45b9db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3bc6708d-3f73-414b-801d-6462dec37ee8"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/hat/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DpadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ccfe3f5-1fa7-440a-b5df-6d909e97f84d"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/hat/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DpadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61bae9c2-6fda-4ca9-8988-70ea35668ca5"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/hat/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DpadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3927c847-e1bc-408b-97f6-ed3ebe3d99c3"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/hat/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DpadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4edb1d6-3948-41e1-b423-ebe1fe274dfe"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21446f46-43f8-4460-94f8-41ff99de8505"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20ae393c-181e-48fb-ae8a-8631f8595e17"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b98e5c56-842b-4c12-95c3-213b497a2e2f"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90ccf7e2-a24d-409e-babc-b01006d33619"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c8a1085-4c28-4933-856b-50b9240dc03f"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca3b1a4b-bc00-4143-8ea2-6cf8b162d880"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""500a3050-4305-4219-a58c-a54c318f06a9"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button20"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Plus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a38b20d3-bf73-4f6d-b14d-baded2b66227"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button21"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Minus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e135231-6ba4-4fef-a8bc-25ed43e5a147"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button25"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PS"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9eadd59-2d62-499f-9794-bc58bd54ebe7"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Share"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1684947f-83e0-44fc-a4dc-665d9b117dc0"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Options"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d969abdc-1beb-48d7-9903-dd977b96eaa4"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8147aac9-c6be-40d4-9acd-2449c6ecf249"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab4f22b2-f4d9-4ed5-b524-00ff8cf9be67"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""164e715f-46b3-4b09-986a-35fd778f09d4"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d7bc42a-13a3-4b2a-aaa7-45ff44da8971"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button22"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db69ca58-dcb5-4493-8d19-19a936ab9cd1"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button23"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75fb711c-fc39-4c97-bdba-c8d7e2d31f35"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/button24"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WheelMiddle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""id"": ""216a5df7-53bb-47e4-98a9-4d0ef7d15ecf"",
            ""actions"": [
                {
                    ""name"": ""Park"",
                    ""type"": ""Button"",
                    ""id"": ""24e5690b-b4f0-45d2-ae10-6628c76bfad2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reverse"",
                    ""type"": ""Button"",
                    ""id"": ""8466ee0f-bbd4-4238-a7a6-83613ade2a7d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Neutral"",
                    ""type"": ""Button"",
                    ""id"": ""4a170662-d52d-452e-863e-dd7cebfa8941"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drive"",
                    ""type"": ""Button"",
                    ""id"": ""fa8ce9e4-fad8-4518-952c-1df8c1d86fcc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""81a55c7a-45ef-4173-8f62-2bf937e82a81"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftIndicator"",
                    ""type"": ""Button"",
                    ""id"": ""fc83733a-f96b-427b-9f85-63b39335a0bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightIndicator"",
                    ""type"": ""Button"",
                    ""id"": ""ffcbfcf4-438a-4771-9765-7d0d4e7197c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e50db1b6-8cd3-459c-a2fe-9cd677d08125"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Park"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db24bad6-8d81-4d5c-8823-f94436cc8f80"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03241c34-1dd2-4a89-9fae-70b6a0738856"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Neutral"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3b39e7d-7084-4ecb-a94e-ead4e06f1766"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d59ba63-3e2c-4966-a22b-d846aa68476c"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cc20eda-4292-4107-bd84-9032ca777540"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftIndicator"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54bffc20-f35f-4a2a-89c5-d6da69f515a8"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightIndicator"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Steering Wheel
        m_SteeringWheel = asset.FindActionMap("Steering Wheel", throwIfNotFound: true);
        m_SteeringWheel_DpadDown = m_SteeringWheel.FindAction("DpadDown", throwIfNotFound: true);
        m_SteeringWheel_DpadUp = m_SteeringWheel.FindAction("DpadUp", throwIfNotFound: true);
        m_SteeringWheel_DpadLeft = m_SteeringWheel.FindAction("DpadLeft", throwIfNotFound: true);
        m_SteeringWheel_DpadRight = m_SteeringWheel.FindAction("DpadRight", throwIfNotFound: true);
        m_SteeringWheel_L1 = m_SteeringWheel.FindAction("L1", throwIfNotFound: true);
        m_SteeringWheel_L2 = m_SteeringWheel.FindAction("L2", throwIfNotFound: true);
        m_SteeringWheel_L3 = m_SteeringWheel.FindAction("L3", throwIfNotFound: true);
        m_SteeringWheel_R1 = m_SteeringWheel.FindAction("R1", throwIfNotFound: true);
        m_SteeringWheel_R2 = m_SteeringWheel.FindAction("R2", throwIfNotFound: true);
        m_SteeringWheel_R3 = m_SteeringWheel.FindAction("R3", throwIfNotFound: true);
        m_SteeringWheel_Plus = m_SteeringWheel.FindAction("Plus", throwIfNotFound: true);
        m_SteeringWheel_Minus = m_SteeringWheel.FindAction("Minus", throwIfNotFound: true);
        m_SteeringWheel_PS = m_SteeringWheel.FindAction("PS", throwIfNotFound: true);
        m_SteeringWheel_Share = m_SteeringWheel.FindAction("Share", throwIfNotFound: true);
        m_SteeringWheel_Options = m_SteeringWheel.FindAction("Options", throwIfNotFound: true);
        m_SteeringWheel_Triangle = m_SteeringWheel.FindAction("Triangle", throwIfNotFound: true);
        m_SteeringWheel_Square = m_SteeringWheel.FindAction("Square", throwIfNotFound: true);
        m_SteeringWheel_Cross = m_SteeringWheel.FindAction("Cross", throwIfNotFound: true);
        m_SteeringWheel_Circle = m_SteeringWheel.FindAction("Circle", throwIfNotFound: true);
        m_SteeringWheel_Wheel = m_SteeringWheel.FindAction("Wheel", throwIfNotFound: true);
        m_SteeringWheel_WheelMiddle = m_SteeringWheel.FindAction("WheelMiddle", throwIfNotFound: true);
        // Keyboard
        m_Keyboard = asset.FindActionMap("Keyboard", throwIfNotFound: true);
        m_Keyboard_Park = m_Keyboard.FindAction("Park", throwIfNotFound: true);
        m_Keyboard_Reverse = m_Keyboard.FindAction("Reverse", throwIfNotFound: true);
        m_Keyboard_Neutral = m_Keyboard.FindAction("Neutral", throwIfNotFound: true);
        m_Keyboard_Drive = m_Keyboard.FindAction("Drive", throwIfNotFound: true);
        m_Keyboard_Scroll = m_Keyboard.FindAction("Scroll", throwIfNotFound: true);
        m_Keyboard_LeftIndicator = m_Keyboard.FindAction("LeftIndicator", throwIfNotFound: true);
        m_Keyboard_RightIndicator = m_Keyboard.FindAction("RightIndicator", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Steering Wheel
    private readonly InputActionMap m_SteeringWheel;
    private List<ISteeringWheelActions> m_SteeringWheelActionsCallbackInterfaces = new List<ISteeringWheelActions>();
    private readonly InputAction m_SteeringWheel_DpadDown;
    private readonly InputAction m_SteeringWheel_DpadUp;
    private readonly InputAction m_SteeringWheel_DpadLeft;
    private readonly InputAction m_SteeringWheel_DpadRight;
    private readonly InputAction m_SteeringWheel_L1;
    private readonly InputAction m_SteeringWheel_L2;
    private readonly InputAction m_SteeringWheel_L3;
    private readonly InputAction m_SteeringWheel_R1;
    private readonly InputAction m_SteeringWheel_R2;
    private readonly InputAction m_SteeringWheel_R3;
    private readonly InputAction m_SteeringWheel_Plus;
    private readonly InputAction m_SteeringWheel_Minus;
    private readonly InputAction m_SteeringWheel_PS;
    private readonly InputAction m_SteeringWheel_Share;
    private readonly InputAction m_SteeringWheel_Options;
    private readonly InputAction m_SteeringWheel_Triangle;
    private readonly InputAction m_SteeringWheel_Square;
    private readonly InputAction m_SteeringWheel_Cross;
    private readonly InputAction m_SteeringWheel_Circle;
    private readonly InputAction m_SteeringWheel_Wheel;
    private readonly InputAction m_SteeringWheel_WheelMiddle;
    public struct SteeringWheelActions
    {
        private @Inputs m_Wrapper;
        public SteeringWheelActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @DpadDown => m_Wrapper.m_SteeringWheel_DpadDown;
        public InputAction @DpadUp => m_Wrapper.m_SteeringWheel_DpadUp;
        public InputAction @DpadLeft => m_Wrapper.m_SteeringWheel_DpadLeft;
        public InputAction @DpadRight => m_Wrapper.m_SteeringWheel_DpadRight;
        public InputAction @L1 => m_Wrapper.m_SteeringWheel_L1;
        public InputAction @L2 => m_Wrapper.m_SteeringWheel_L2;
        public InputAction @L3 => m_Wrapper.m_SteeringWheel_L3;
        public InputAction @R1 => m_Wrapper.m_SteeringWheel_R1;
        public InputAction @R2 => m_Wrapper.m_SteeringWheel_R2;
        public InputAction @R3 => m_Wrapper.m_SteeringWheel_R3;
        public InputAction @Plus => m_Wrapper.m_SteeringWheel_Plus;
        public InputAction @Minus => m_Wrapper.m_SteeringWheel_Minus;
        public InputAction @PS => m_Wrapper.m_SteeringWheel_PS;
        public InputAction @Share => m_Wrapper.m_SteeringWheel_Share;
        public InputAction @Options => m_Wrapper.m_SteeringWheel_Options;
        public InputAction @Triangle => m_Wrapper.m_SteeringWheel_Triangle;
        public InputAction @Square => m_Wrapper.m_SteeringWheel_Square;
        public InputAction @Cross => m_Wrapper.m_SteeringWheel_Cross;
        public InputAction @Circle => m_Wrapper.m_SteeringWheel_Circle;
        public InputAction @Wheel => m_Wrapper.m_SteeringWheel_Wheel;
        public InputAction @WheelMiddle => m_Wrapper.m_SteeringWheel_WheelMiddle;
        public InputActionMap Get() { return m_Wrapper.m_SteeringWheel; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SteeringWheelActions set) { return set.Get(); }
        public void AddCallbacks(ISteeringWheelActions instance)
        {
            if (instance == null || m_Wrapper.m_SteeringWheelActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SteeringWheelActionsCallbackInterfaces.Add(instance);
            @DpadDown.started += instance.OnDpadDown;
            @DpadDown.performed += instance.OnDpadDown;
            @DpadDown.canceled += instance.OnDpadDown;
            @DpadUp.started += instance.OnDpadUp;
            @DpadUp.performed += instance.OnDpadUp;
            @DpadUp.canceled += instance.OnDpadUp;
            @DpadLeft.started += instance.OnDpadLeft;
            @DpadLeft.performed += instance.OnDpadLeft;
            @DpadLeft.canceled += instance.OnDpadLeft;
            @DpadRight.started += instance.OnDpadRight;
            @DpadRight.performed += instance.OnDpadRight;
            @DpadRight.canceled += instance.OnDpadRight;
            @L1.started += instance.OnL1;
            @L1.performed += instance.OnL1;
            @L1.canceled += instance.OnL1;
            @L2.started += instance.OnL2;
            @L2.performed += instance.OnL2;
            @L2.canceled += instance.OnL2;
            @L3.started += instance.OnL3;
            @L3.performed += instance.OnL3;
            @L3.canceled += instance.OnL3;
            @R1.started += instance.OnR1;
            @R1.performed += instance.OnR1;
            @R1.canceled += instance.OnR1;
            @R2.started += instance.OnR2;
            @R2.performed += instance.OnR2;
            @R2.canceled += instance.OnR2;
            @R3.started += instance.OnR3;
            @R3.performed += instance.OnR3;
            @R3.canceled += instance.OnR3;
            @Plus.started += instance.OnPlus;
            @Plus.performed += instance.OnPlus;
            @Plus.canceled += instance.OnPlus;
            @Minus.started += instance.OnMinus;
            @Minus.performed += instance.OnMinus;
            @Minus.canceled += instance.OnMinus;
            @PS.started += instance.OnPS;
            @PS.performed += instance.OnPS;
            @PS.canceled += instance.OnPS;
            @Share.started += instance.OnShare;
            @Share.performed += instance.OnShare;
            @Share.canceled += instance.OnShare;
            @Options.started += instance.OnOptions;
            @Options.performed += instance.OnOptions;
            @Options.canceled += instance.OnOptions;
            @Triangle.started += instance.OnTriangle;
            @Triangle.performed += instance.OnTriangle;
            @Triangle.canceled += instance.OnTriangle;
            @Square.started += instance.OnSquare;
            @Square.performed += instance.OnSquare;
            @Square.canceled += instance.OnSquare;
            @Cross.started += instance.OnCross;
            @Cross.performed += instance.OnCross;
            @Cross.canceled += instance.OnCross;
            @Circle.started += instance.OnCircle;
            @Circle.performed += instance.OnCircle;
            @Circle.canceled += instance.OnCircle;
            @Wheel.started += instance.OnWheel;
            @Wheel.performed += instance.OnWheel;
            @Wheel.canceled += instance.OnWheel;
            @WheelMiddle.started += instance.OnWheelMiddle;
            @WheelMiddle.performed += instance.OnWheelMiddle;
            @WheelMiddle.canceled += instance.OnWheelMiddle;
        }

        private void UnregisterCallbacks(ISteeringWheelActions instance)
        {
            @DpadDown.started -= instance.OnDpadDown;
            @DpadDown.performed -= instance.OnDpadDown;
            @DpadDown.canceled -= instance.OnDpadDown;
            @DpadUp.started -= instance.OnDpadUp;
            @DpadUp.performed -= instance.OnDpadUp;
            @DpadUp.canceled -= instance.OnDpadUp;
            @DpadLeft.started -= instance.OnDpadLeft;
            @DpadLeft.performed -= instance.OnDpadLeft;
            @DpadLeft.canceled -= instance.OnDpadLeft;
            @DpadRight.started -= instance.OnDpadRight;
            @DpadRight.performed -= instance.OnDpadRight;
            @DpadRight.canceled -= instance.OnDpadRight;
            @L1.started -= instance.OnL1;
            @L1.performed -= instance.OnL1;
            @L1.canceled -= instance.OnL1;
            @L2.started -= instance.OnL2;
            @L2.performed -= instance.OnL2;
            @L2.canceled -= instance.OnL2;
            @L3.started -= instance.OnL3;
            @L3.performed -= instance.OnL3;
            @L3.canceled -= instance.OnL3;
            @R1.started -= instance.OnR1;
            @R1.performed -= instance.OnR1;
            @R1.canceled -= instance.OnR1;
            @R2.started -= instance.OnR2;
            @R2.performed -= instance.OnR2;
            @R2.canceled -= instance.OnR2;
            @R3.started -= instance.OnR3;
            @R3.performed -= instance.OnR3;
            @R3.canceled -= instance.OnR3;
            @Plus.started -= instance.OnPlus;
            @Plus.performed -= instance.OnPlus;
            @Plus.canceled -= instance.OnPlus;
            @Minus.started -= instance.OnMinus;
            @Minus.performed -= instance.OnMinus;
            @Minus.canceled -= instance.OnMinus;
            @PS.started -= instance.OnPS;
            @PS.performed -= instance.OnPS;
            @PS.canceled -= instance.OnPS;
            @Share.started -= instance.OnShare;
            @Share.performed -= instance.OnShare;
            @Share.canceled -= instance.OnShare;
            @Options.started -= instance.OnOptions;
            @Options.performed -= instance.OnOptions;
            @Options.canceled -= instance.OnOptions;
            @Triangle.started -= instance.OnTriangle;
            @Triangle.performed -= instance.OnTriangle;
            @Triangle.canceled -= instance.OnTriangle;
            @Square.started -= instance.OnSquare;
            @Square.performed -= instance.OnSquare;
            @Square.canceled -= instance.OnSquare;
            @Cross.started -= instance.OnCross;
            @Cross.performed -= instance.OnCross;
            @Cross.canceled -= instance.OnCross;
            @Circle.started -= instance.OnCircle;
            @Circle.performed -= instance.OnCircle;
            @Circle.canceled -= instance.OnCircle;
            @Wheel.started -= instance.OnWheel;
            @Wheel.performed -= instance.OnWheel;
            @Wheel.canceled -= instance.OnWheel;
            @WheelMiddle.started -= instance.OnWheelMiddle;
            @WheelMiddle.performed -= instance.OnWheelMiddle;
            @WheelMiddle.canceled -= instance.OnWheelMiddle;
        }

        public void RemoveCallbacks(ISteeringWheelActions instance)
        {
            if (m_Wrapper.m_SteeringWheelActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISteeringWheelActions instance)
        {
            foreach (var item in m_Wrapper.m_SteeringWheelActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SteeringWheelActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SteeringWheelActions @SteeringWheel => new SteeringWheelActions(this);

    // Keyboard
    private readonly InputActionMap m_Keyboard;
    private List<IKeyboardActions> m_KeyboardActionsCallbackInterfaces = new List<IKeyboardActions>();
    private readonly InputAction m_Keyboard_Park;
    private readonly InputAction m_Keyboard_Reverse;
    private readonly InputAction m_Keyboard_Neutral;
    private readonly InputAction m_Keyboard_Drive;
    private readonly InputAction m_Keyboard_Scroll;
    private readonly InputAction m_Keyboard_LeftIndicator;
    private readonly InputAction m_Keyboard_RightIndicator;
    public struct KeyboardActions
    {
        private @Inputs m_Wrapper;
        public KeyboardActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Park => m_Wrapper.m_Keyboard_Park;
        public InputAction @Reverse => m_Wrapper.m_Keyboard_Reverse;
        public InputAction @Neutral => m_Wrapper.m_Keyboard_Neutral;
        public InputAction @Drive => m_Wrapper.m_Keyboard_Drive;
        public InputAction @Scroll => m_Wrapper.m_Keyboard_Scroll;
        public InputAction @LeftIndicator => m_Wrapper.m_Keyboard_LeftIndicator;
        public InputAction @RightIndicator => m_Wrapper.m_Keyboard_RightIndicator;
        public InputActionMap Get() { return m_Wrapper.m_Keyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardActions set) { return set.Get(); }
        public void AddCallbacks(IKeyboardActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyboardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyboardActionsCallbackInterfaces.Add(instance);
            @Park.started += instance.OnPark;
            @Park.performed += instance.OnPark;
            @Park.canceled += instance.OnPark;
            @Reverse.started += instance.OnReverse;
            @Reverse.performed += instance.OnReverse;
            @Reverse.canceled += instance.OnReverse;
            @Neutral.started += instance.OnNeutral;
            @Neutral.performed += instance.OnNeutral;
            @Neutral.canceled += instance.OnNeutral;
            @Drive.started += instance.OnDrive;
            @Drive.performed += instance.OnDrive;
            @Drive.canceled += instance.OnDrive;
            @Scroll.started += instance.OnScroll;
            @Scroll.performed += instance.OnScroll;
            @Scroll.canceled += instance.OnScroll;
            @LeftIndicator.started += instance.OnLeftIndicator;
            @LeftIndicator.performed += instance.OnLeftIndicator;
            @LeftIndicator.canceled += instance.OnLeftIndicator;
            @RightIndicator.started += instance.OnRightIndicator;
            @RightIndicator.performed += instance.OnRightIndicator;
            @RightIndicator.canceled += instance.OnRightIndicator;
        }

        private void UnregisterCallbacks(IKeyboardActions instance)
        {
            @Park.started -= instance.OnPark;
            @Park.performed -= instance.OnPark;
            @Park.canceled -= instance.OnPark;
            @Reverse.started -= instance.OnReverse;
            @Reverse.performed -= instance.OnReverse;
            @Reverse.canceled -= instance.OnReverse;
            @Neutral.started -= instance.OnNeutral;
            @Neutral.performed -= instance.OnNeutral;
            @Neutral.canceled -= instance.OnNeutral;
            @Drive.started -= instance.OnDrive;
            @Drive.performed -= instance.OnDrive;
            @Drive.canceled -= instance.OnDrive;
            @Scroll.started -= instance.OnScroll;
            @Scroll.performed -= instance.OnScroll;
            @Scroll.canceled -= instance.OnScroll;
            @LeftIndicator.started -= instance.OnLeftIndicator;
            @LeftIndicator.performed -= instance.OnLeftIndicator;
            @LeftIndicator.canceled -= instance.OnLeftIndicator;
            @RightIndicator.started -= instance.OnRightIndicator;
            @RightIndicator.performed -= instance.OnRightIndicator;
            @RightIndicator.canceled -= instance.OnRightIndicator;
        }

        public void RemoveCallbacks(IKeyboardActions instance)
        {
            if (m_Wrapper.m_KeyboardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyboardActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyboardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyboardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyboardActions @Keyboard => new KeyboardActions(this);
    public interface ISteeringWheelActions
    {
        void OnDpadDown(InputAction.CallbackContext context);
        void OnDpadUp(InputAction.CallbackContext context);
        void OnDpadLeft(InputAction.CallbackContext context);
        void OnDpadRight(InputAction.CallbackContext context);
        void OnL1(InputAction.CallbackContext context);
        void OnL2(InputAction.CallbackContext context);
        void OnL3(InputAction.CallbackContext context);
        void OnR1(InputAction.CallbackContext context);
        void OnR2(InputAction.CallbackContext context);
        void OnR3(InputAction.CallbackContext context);
        void OnPlus(InputAction.CallbackContext context);
        void OnMinus(InputAction.CallbackContext context);
        void OnPS(InputAction.CallbackContext context);
        void OnShare(InputAction.CallbackContext context);
        void OnOptions(InputAction.CallbackContext context);
        void OnTriangle(InputAction.CallbackContext context);
        void OnSquare(InputAction.CallbackContext context);
        void OnCross(InputAction.CallbackContext context);
        void OnCircle(InputAction.CallbackContext context);
        void OnWheel(InputAction.CallbackContext context);
        void OnWheelMiddle(InputAction.CallbackContext context);
    }
    public interface IKeyboardActions
    {
        void OnPark(InputAction.CallbackContext context);
        void OnReverse(InputAction.CallbackContext context);
        void OnNeutral(InputAction.CallbackContext context);
        void OnDrive(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
        void OnLeftIndicator(InputAction.CallbackContext context);
        void OnRightIndicator(InputAction.CallbackContext context);
    }
}
